version: '3.9'
services:
  api:
    build: .
    environment:
      - PORT=8000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=${REDIS_TLS}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: leaderboard
    volumes:
      - mongo_data:/data/db
  worker:
    build: .
    command: ["node", "src/workers/gameResultWorker.js"]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=${REDIS_TLS}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - redis
      - mongo
  aggregator:
    build: .
    command: ["node", "src/workers/aggregatorWorker.js"]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=${REDIS_TLS}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - redis
volumes:
  mongo_data:


